# Generated by Django 5.1.2 on 2024-10-31 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('foto', models.DateField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('año', models.DateField()),
                ('portada', models.ImageField(upload_to='')),
                ('actores', models.ManyToManyField(to='appPeliculas.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPeliculas.director')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
