# Generated by Django 5.1.2 on 2024-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='director',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='portada',
        ),
        migrations.AddField(
            model_name='actor',
            name='url_imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='url_imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='url_imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
