# Generated by Django 5.1.2 on 2024-10-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0002_remove_actor_foto_remove_director_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='año',
            new_name='fecha',
        ),
    ]
