# Generated by Django 5.1.2 on 2024-11-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0003_rename_año_pelicula_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
