# Generated by Django 5.1.2 on 2024-11-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
