# Generated by Django 5.1.2 on 2024-11-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0005_subscriptor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptor',
            new_name='Suscriptor',
        ),
    ]
