# Generated by Django 5.1.2 on 2024-12-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0006_rename_subscriptor_suscriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(to='appPeliculas.genero'),
        ),
    ]
